version: 2
jobs:
  build:
      docker:
        - image: circleci/python:3.6
      working_directory: ~/tenant-base

      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
        - run:
            name: Install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}

        - run:
            name: Run pylint
            command: |
              . venv/bin/activate
              pylint lambda_function.py

        - run:
            name: Build and test
            command: |
              . venv/bin/activate
              python3 -m pytest --cov-report term-missing --cov=main tests/ -s
              coveralls
